use crossterm::event::{KeyCode, KeyEvent, KeyModifiers};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum InputAction {
    None,
    Quit,
    ToggleHelp,
    NextFocus,
    PrevFocus,
    MoveUp,
    MoveDown,
    ToggleSelect,
    ClearSelection,
    Activate,
    Deal,
    PlaySelected,
    DiscardSelected,
    SkipBlind,
    EnterOrLeaveShop,
    RerollShop,
    BuySelected,
    PickSelectedPack,
    SkipPack,
    NextBlind,
    UseConsumable,
    SellJoker,
    SelectNumber(u8),
    SaveState,
    LoadState,
}

pub fn map_key(key: KeyEvent) -> InputAction {
    match key.code {
        KeyCode::Esc => InputAction::ClearSelection,
        KeyCode::Tab => InputAction::NextFocus,
        KeyCode::BackTab => InputAction::PrevFocus,
        KeyCode::Up => InputAction::MoveUp,
        KeyCode::Down => InputAction::MoveDown,
        KeyCode::Enter => InputAction::Activate,
        KeyCode::Char('q') => InputAction::Quit,
        KeyCode::Char('?') => InputAction::ToggleHelp,
        KeyCode::Char(' ') => InputAction::ToggleSelect,
        KeyCode::Char('k') => {
            if key.modifiers.contains(KeyModifiers::SHIFT) {
                InputAction::SkipBlind
            } else {
                InputAction::MoveUp
            }
        }
        KeyCode::Char('j') => InputAction::MoveDown,
        KeyCode::Char('d') => InputAction::Deal,
        KeyCode::Char('p') => InputAction::PlaySelected,
        KeyCode::Char('x') => InputAction::DiscardSelected,
        KeyCode::Char('s') if key.modifiers.contains(KeyModifiers::CONTROL) => {
            InputAction::SaveState
        }
        KeyCode::Char('l') if key.modifiers.contains(KeyModifiers::CONTROL) => {
            InputAction::LoadState
        }
        KeyCode::Char('s') => InputAction::EnterOrLeaveShop,
        KeyCode::Char('r') => InputAction::RerollShop,
        KeyCode::Char('b') => InputAction::BuySelected,
        KeyCode::Char('c') => InputAction::PickSelectedPack,
        KeyCode::Char('z') => InputAction::SkipPack,
        KeyCode::Char('n') => InputAction::NextBlind,
        KeyCode::Char('u') => InputAction::UseConsumable,
        KeyCode::Char('v') => InputAction::SellJoker,
        KeyCode::Char(ch) if ch.is_ascii_digit() => InputAction::SelectNumber(ch as u8 - b'0'),
        KeyCode::Char('S') => InputAction::SaveState,
        KeyCode::Char('L') => InputAction::LoadState,
        _ => InputAction::None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    macro_rules! key_case {
        ($name:ident, $code:expr, $mods:expr, $expected:expr) => {
            #[test]
            fn $name() {
                let key = KeyEvent::new($code, $mods);
                assert_eq!(map_key(key), $expected);
            }
        };
    }

    key_case!(
        map_deal,
        KeyCode::Char('d'),
        KeyModifiers::NONE,
        InputAction::Deal
    );
    key_case!(
        map_play,
        KeyCode::Char('p'),
        KeyModifiers::NONE,
        InputAction::PlaySelected
    );
    key_case!(
        map_quit,
        KeyCode::Char('q'),
        KeyModifiers::NONE,
        InputAction::Quit
    );
    key_case!(
        map_help,
        KeyCode::Char('?'),
        KeyModifiers::NONE,
        InputAction::ToggleHelp
    );
    key_case!(
        map_space,
        KeyCode::Char(' '),
        KeyModifiers::NONE,
        InputAction::ToggleSelect
    );
    key_case!(
        map_k,
        KeyCode::Char('k'),
        KeyModifiers::NONE,
        InputAction::MoveUp
    );
    key_case!(
        map_shift_k,
        KeyCode::Char('k'),
        KeyModifiers::SHIFT,
        InputAction::SkipBlind
    );
    key_case!(
        map_j,
        KeyCode::Char('j'),
        KeyModifiers::NONE,
        InputAction::MoveDown
    );
    key_case!(
        map_ctrl_s,
        KeyCode::Char('s'),
        KeyModifiers::CONTROL,
        InputAction::SaveState
    );
    key_case!(
        map_ctrl_l,
        KeyCode::Char('l'),
        KeyModifiers::CONTROL,
        InputAction::LoadState
    );
    key_case!(
        map_s,
        KeyCode::Char('s'),
        KeyModifiers::NONE,
        InputAction::EnterOrLeaveShop
    );
    key_case!(
        map_r,
        KeyCode::Char('r'),
        KeyModifiers::NONE,
        InputAction::RerollShop
    );
    key_case!(
        map_b,
        KeyCode::Char('b'),
        KeyModifiers::NONE,
        InputAction::BuySelected
    );
    key_case!(
        map_c,
        KeyCode::Char('c'),
        KeyModifiers::NONE,
        InputAction::PickSelectedPack
    );
    key_case!(
        map_z,
        KeyCode::Char('z'),
        KeyModifiers::NONE,
        InputAction::SkipPack
    );
    key_case!(
        map_n,
        KeyCode::Char('n'),
        KeyModifiers::NONE,
        InputAction::NextBlind
    );
    key_case!(
        map_u,
        KeyCode::Char('u'),
        KeyModifiers::NONE,
        InputAction::UseConsumable
    );
    key_case!(
        map_v,
        KeyCode::Char('v'),
        KeyModifiers::NONE,
        InputAction::SellJoker
    );
    key_case!(
        map_upper_s,
        KeyCode::Char('S'),
        KeyModifiers::SHIFT,
        InputAction::SaveState
    );
    key_case!(
        map_upper_l,
        KeyCode::Char('L'),
        KeyModifiers::SHIFT,
        InputAction::LoadState
    );
    key_case!(
        map_tab,
        KeyCode::Tab,
        KeyModifiers::NONE,
        InputAction::NextFocus
    );
    key_case!(
        map_backtab,
        KeyCode::BackTab,
        KeyModifiers::SHIFT,
        InputAction::PrevFocus
    );
    key_case!(map_up, KeyCode::Up, KeyModifiers::NONE, InputAction::MoveUp);
    key_case!(
        map_down,
        KeyCode::Down,
        KeyModifiers::NONE,
        InputAction::MoveDown
    );
    key_case!(
        map_enter,
        KeyCode::Enter,
        KeyModifiers::NONE,
        InputAction::Activate
    );
    key_case!(
        map_esc,
        KeyCode::Esc,
        KeyModifiers::NONE,
        InputAction::ClearSelection
    );

    key_case!(
        map_digit_0,
        KeyCode::Char('0'),
        KeyModifiers::NONE,
        InputAction::SelectNumber(0)
    );
    key_case!(
        map_digit_1,
        KeyCode::Char('1'),
        KeyModifiers::NONE,
        InputAction::SelectNumber(1)
    );
    key_case!(
        map_digit_2,
        KeyCode::Char('2'),
        KeyModifiers::NONE,
        InputAction::SelectNumber(2)
    );
    key_case!(
        map_digit_3,
        KeyCode::Char('3'),
        KeyModifiers::NONE,
        InputAction::SelectNumber(3)
    );
    key_case!(
        map_digit_4,
        KeyCode::Char('4'),
        KeyModifiers::NONE,
        InputAction::SelectNumber(4)
    );
    key_case!(
        map_digit_5,
        KeyCode::Char('5'),
        KeyModifiers::NONE,
        InputAction::SelectNumber(5)
    );
    key_case!(
        map_digit_6,
        KeyCode::Char('6'),
        KeyModifiers::NONE,
        InputAction::SelectNumber(6)
    );
    key_case!(
        map_digit_7,
        KeyCode::Char('7'),
        KeyModifiers::NONE,
        InputAction::SelectNumber(7)
    );
    key_case!(
        map_digit_8,
        KeyCode::Char('8'),
        KeyModifiers::NONE,
        InputAction::SelectNumber(8)
    );
    key_case!(
        map_digit_9,
        KeyCode::Char('9'),
        KeyModifiers::NONE,
        InputAction::SelectNumber(9)
    );

    key_case!(
        unknown_ascii_0,
        KeyCode::Char('a'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_1,
        KeyCode::Char('e'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_2,
        KeyCode::Char('f'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_3,
        KeyCode::Char('g'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_4,
        KeyCode::Char('h'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_5,
        KeyCode::Char('i'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_6,
        KeyCode::Char('m'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_7,
        KeyCode::Char('o'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_8,
        KeyCode::Char('t'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_9,
        KeyCode::Char('w'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_10,
        KeyCode::Char('y'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_11,
        KeyCode::Char('A'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_12,
        KeyCode::Char('B'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_13,
        KeyCode::Char('C'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_14,
        KeyCode::Char('D'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_15,
        KeyCode::Char('E'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_16,
        KeyCode::Char('F'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_17,
        KeyCode::Char('G'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_18,
        KeyCode::Char('H'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_19,
        KeyCode::Char('I'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_20,
        KeyCode::Char('J'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_21,
        KeyCode::Char('K'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_22,
        KeyCode::Char('M'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_23,
        KeyCode::Char('N'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_24,
        KeyCode::Char('O'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_25,
        KeyCode::Char('P'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_26,
        KeyCode::Char('Q'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_27,
        KeyCode::Char('R'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_28,
        KeyCode::Char('T'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_29,
        KeyCode::Char('U'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_30,
        KeyCode::Char('V'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_31,
        KeyCode::Char('W'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_32,
        KeyCode::Char('X'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_33,
        KeyCode::Char('Y'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_34,
        KeyCode::Char('Z'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_35,
        KeyCode::Char('!'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_36,
        KeyCode::Char('"'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_37,
        KeyCode::Char('#'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_38,
        KeyCode::Char('$'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_39,
        KeyCode::Char('%'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_40,
        KeyCode::Char('&'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_41,
        KeyCode::Char('\''),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_42,
        KeyCode::Char('('),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_43,
        KeyCode::Char(')'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_44,
        KeyCode::Char('*'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_45,
        KeyCode::Char('+'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_46,
        KeyCode::Char(','),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_47,
        KeyCode::Char('-'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_48,
        KeyCode::Char('.'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_49,
        KeyCode::Char('/'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_50,
        KeyCode::Char(':'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_51,
        KeyCode::Char(';'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_52,
        KeyCode::Char('<'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_53,
        KeyCode::Char('='),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_54,
        KeyCode::Char('>'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_55,
        KeyCode::Char('@'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_56,
        KeyCode::Char('['),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_57,
        KeyCode::Char('\\'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_58,
        KeyCode::Char(']'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_59,
        KeyCode::Char('^'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_60,
        KeyCode::Char('_'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_61,
        KeyCode::Char('`'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_62,
        KeyCode::Char('{'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_63,
        KeyCode::Char('|'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_64,
        KeyCode::Char('}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_ascii_65,
        KeyCode::Char('~'),
        KeyModifiers::NONE,
        InputAction::None
    );

    key_case!(
        unknown_unicode_0,
        KeyCode::Char('\u{80}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_1,
        KeyCode::Char('\u{81}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_2,
        KeyCode::Char('\u{82}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_3,
        KeyCode::Char('\u{83}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_4,
        KeyCode::Char('\u{84}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_5,
        KeyCode::Char('\u{85}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_6,
        KeyCode::Char('\u{86}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_7,
        KeyCode::Char('\u{87}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_8,
        KeyCode::Char('\u{88}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_9,
        KeyCode::Char('\u{89}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_10,
        KeyCode::Char('\u{8a}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_11,
        KeyCode::Char('\u{8b}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_12,
        KeyCode::Char('\u{8c}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_13,
        KeyCode::Char('\u{8d}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_14,
        KeyCode::Char('\u{8e}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_15,
        KeyCode::Char('\u{8f}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_16,
        KeyCode::Char('\u{90}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_17,
        KeyCode::Char('\u{91}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_18,
        KeyCode::Char('\u{92}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_19,
        KeyCode::Char('\u{93}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_20,
        KeyCode::Char('\u{94}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_21,
        KeyCode::Char('\u{95}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_22,
        KeyCode::Char('\u{96}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_23,
        KeyCode::Char('\u{97}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_24,
        KeyCode::Char('\u{98}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_25,
        KeyCode::Char('\u{99}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_26,
        KeyCode::Char('\u{9a}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_27,
        KeyCode::Char('\u{9b}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_28,
        KeyCode::Char('\u{9c}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_29,
        KeyCode::Char('\u{9d}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_30,
        KeyCode::Char('\u{9e}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_31,
        KeyCode::Char('\u{9f}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_32,
        KeyCode::Char('\u{a0}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_33,
        KeyCode::Char('\u{a1}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_34,
        KeyCode::Char('\u{a2}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_35,
        KeyCode::Char('\u{a3}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_36,
        KeyCode::Char('\u{a4}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_37,
        KeyCode::Char('\u{a5}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_38,
        KeyCode::Char('\u{a6}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_39,
        KeyCode::Char('\u{a7}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_40,
        KeyCode::Char('\u{a8}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_41,
        KeyCode::Char('\u{a9}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_42,
        KeyCode::Char('\u{aa}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_43,
        KeyCode::Char('\u{ab}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_44,
        KeyCode::Char('\u{ac}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_45,
        KeyCode::Char('\u{ad}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_46,
        KeyCode::Char('\u{ae}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_47,
        KeyCode::Char('\u{af}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_48,
        KeyCode::Char('\u{b0}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_49,
        KeyCode::Char('\u{b1}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_50,
        KeyCode::Char('\u{b2}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_51,
        KeyCode::Char('\u{b3}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_52,
        KeyCode::Char('\u{b4}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_53,
        KeyCode::Char('\u{b5}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_54,
        KeyCode::Char('\u{b6}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_55,
        KeyCode::Char('\u{b7}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_56,
        KeyCode::Char('\u{b8}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_57,
        KeyCode::Char('\u{b9}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_58,
        KeyCode::Char('\u{ba}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_59,
        KeyCode::Char('\u{bb}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_60,
        KeyCode::Char('\u{bc}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_61,
        KeyCode::Char('\u{bd}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_62,
        KeyCode::Char('\u{be}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_63,
        KeyCode::Char('\u{bf}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_64,
        KeyCode::Char('\u{c0}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_65,
        KeyCode::Char('\u{c1}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_66,
        KeyCode::Char('\u{c2}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_67,
        KeyCode::Char('\u{c3}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_68,
        KeyCode::Char('\u{c4}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_69,
        KeyCode::Char('\u{c5}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_70,
        KeyCode::Char('\u{c6}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_71,
        KeyCode::Char('\u{c7}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_72,
        KeyCode::Char('\u{c8}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_73,
        KeyCode::Char('\u{c9}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_74,
        KeyCode::Char('\u{ca}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_75,
        KeyCode::Char('\u{cb}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_76,
        KeyCode::Char('\u{cc}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_77,
        KeyCode::Char('\u{cd}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_78,
        KeyCode::Char('\u{ce}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_79,
        KeyCode::Char('\u{cf}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_80,
        KeyCode::Char('\u{d0}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_81,
        KeyCode::Char('\u{d1}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_82,
        KeyCode::Char('\u{d2}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_83,
        KeyCode::Char('\u{d3}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_84,
        KeyCode::Char('\u{d4}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_85,
        KeyCode::Char('\u{d5}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_86,
        KeyCode::Char('\u{d6}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_87,
        KeyCode::Char('\u{d7}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_88,
        KeyCode::Char('\u{d8}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_89,
        KeyCode::Char('\u{d9}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_90,
        KeyCode::Char('\u{da}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_91,
        KeyCode::Char('\u{db}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_92,
        KeyCode::Char('\u{dc}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_93,
        KeyCode::Char('\u{dd}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_94,
        KeyCode::Char('\u{de}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_95,
        KeyCode::Char('\u{df}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_96,
        KeyCode::Char('\u{e0}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_97,
        KeyCode::Char('\u{e1}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_98,
        KeyCode::Char('\u{e2}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_99,
        KeyCode::Char('\u{e3}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_100,
        KeyCode::Char('\u{e4}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_101,
        KeyCode::Char('\u{e5}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_102,
        KeyCode::Char('\u{e6}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_103,
        KeyCode::Char('\u{e7}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_104,
        KeyCode::Char('\u{e8}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_105,
        KeyCode::Char('\u{e9}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_106,
        KeyCode::Char('\u{ea}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_107,
        KeyCode::Char('\u{eb}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_108,
        KeyCode::Char('\u{ec}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_109,
        KeyCode::Char('\u{ed}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_110,
        KeyCode::Char('\u{ee}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_111,
        KeyCode::Char('\u{ef}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_112,
        KeyCode::Char('\u{f0}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_113,
        KeyCode::Char('\u{f1}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_114,
        KeyCode::Char('\u{f2}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_115,
        KeyCode::Char('\u{f3}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_116,
        KeyCode::Char('\u{f4}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_117,
        KeyCode::Char('\u{f5}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_118,
        KeyCode::Char('\u{f6}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_119,
        KeyCode::Char('\u{f7}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_120,
        KeyCode::Char('\u{f8}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_121,
        KeyCode::Char('\u{f9}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_122,
        KeyCode::Char('\u{fa}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_123,
        KeyCode::Char('\u{fb}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_124,
        KeyCode::Char('\u{fc}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_125,
        KeyCode::Char('\u{fd}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_126,
        KeyCode::Char('\u{fe}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_127,
        KeyCode::Char('\u{ff}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_128,
        KeyCode::Char('\u{100}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_129,
        KeyCode::Char('\u{101}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_130,
        KeyCode::Char('\u{102}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_131,
        KeyCode::Char('\u{103}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_132,
        KeyCode::Char('\u{104}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_133,
        KeyCode::Char('\u{105}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_134,
        KeyCode::Char('\u{106}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_135,
        KeyCode::Char('\u{107}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_136,
        KeyCode::Char('\u{108}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_137,
        KeyCode::Char('\u{109}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_138,
        KeyCode::Char('\u{10a}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_139,
        KeyCode::Char('\u{10b}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_140,
        KeyCode::Char('\u{10c}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_141,
        KeyCode::Char('\u{10d}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_142,
        KeyCode::Char('\u{10e}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_143,
        KeyCode::Char('\u{10f}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_144,
        KeyCode::Char('\u{110}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_145,
        KeyCode::Char('\u{111}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_146,
        KeyCode::Char('\u{112}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_147,
        KeyCode::Char('\u{113}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_148,
        KeyCode::Char('\u{114}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_149,
        KeyCode::Char('\u{115}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_150,
        KeyCode::Char('\u{116}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_151,
        KeyCode::Char('\u{117}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_152,
        KeyCode::Char('\u{118}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_153,
        KeyCode::Char('\u{119}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_154,
        KeyCode::Char('\u{11a}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_155,
        KeyCode::Char('\u{11b}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_156,
        KeyCode::Char('\u{11c}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_157,
        KeyCode::Char('\u{11d}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_158,
        KeyCode::Char('\u{11e}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_159,
        KeyCode::Char('\u{11f}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_160,
        KeyCode::Char('\u{120}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_161,
        KeyCode::Char('\u{121}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_162,
        KeyCode::Char('\u{122}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_163,
        KeyCode::Char('\u{123}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_164,
        KeyCode::Char('\u{124}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_165,
        KeyCode::Char('\u{125}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_166,
        KeyCode::Char('\u{126}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_167,
        KeyCode::Char('\u{127}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_168,
        KeyCode::Char('\u{128}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_169,
        KeyCode::Char('\u{129}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_170,
        KeyCode::Char('\u{12a}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_171,
        KeyCode::Char('\u{12b}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_172,
        KeyCode::Char('\u{12c}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_173,
        KeyCode::Char('\u{12d}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_174,
        KeyCode::Char('\u{12e}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_175,
        KeyCode::Char('\u{12f}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_176,
        KeyCode::Char('\u{130}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_177,
        KeyCode::Char('\u{131}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_178,
        KeyCode::Char('\u{132}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_179,
        KeyCode::Char('\u{133}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_180,
        KeyCode::Char('\u{134}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_181,
        KeyCode::Char('\u{135}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_182,
        KeyCode::Char('\u{136}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_183,
        KeyCode::Char('\u{137}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_184,
        KeyCode::Char('\u{138}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_185,
        KeyCode::Char('\u{139}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_186,
        KeyCode::Char('\u{13a}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_187,
        KeyCode::Char('\u{13b}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_188,
        KeyCode::Char('\u{13c}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_189,
        KeyCode::Char('\u{13d}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_190,
        KeyCode::Char('\u{13e}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_191,
        KeyCode::Char('\u{13f}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_192,
        KeyCode::Char('\u{140}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_193,
        KeyCode::Char('\u{141}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_194,
        KeyCode::Char('\u{142}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_195,
        KeyCode::Char('\u{143}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_196,
        KeyCode::Char('\u{144}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_197,
        KeyCode::Char('\u{145}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_198,
        KeyCode::Char('\u{146}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_199,
        KeyCode::Char('\u{147}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_200,
        KeyCode::Char('\u{148}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_201,
        KeyCode::Char('\u{149}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_202,
        KeyCode::Char('\u{14a}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_203,
        KeyCode::Char('\u{14b}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_204,
        KeyCode::Char('\u{14c}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_205,
        KeyCode::Char('\u{14d}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_206,
        KeyCode::Char('\u{14e}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_207,
        KeyCode::Char('\u{14f}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_208,
        KeyCode::Char('\u{150}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_209,
        KeyCode::Char('\u{151}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_210,
        KeyCode::Char('\u{152}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_211,
        KeyCode::Char('\u{153}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_212,
        KeyCode::Char('\u{154}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_213,
        KeyCode::Char('\u{155}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_214,
        KeyCode::Char('\u{156}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_215,
        KeyCode::Char('\u{157}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_216,
        KeyCode::Char('\u{158}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_217,
        KeyCode::Char('\u{159}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_218,
        KeyCode::Char('\u{15a}'),
        KeyModifiers::NONE,
        InputAction::None
    );
    key_case!(
        unknown_unicode_219,
        KeyCode::Char('\u{15b}'),
        KeyModifiers::NONE,
        InputAction::None
    );

    #[test]
    fn unsupported_non_char_key_is_none() {
        assert_eq!(
            map_key(KeyEvent::new(KeyCode::Left, KeyModifiers::NONE)),
            InputAction::None
        );
    }
}
